service: product-service
frameworkVersion: '2'
variablesResolutionMode: 20210219

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  iamRoleStatements:
    - Effect: "Allow"
      Action: "sqs:*"
      Resource:
        Fn::GetAtt:
          - CatalogItemsQueue
          - Arn
    - Effect: "Allow"
      Action: "sns:*"
      Resource:
        Ref: CreateProductTopic

environment:
  SNS_TOPIC_ARN:
    Ref: CreateProductTopic

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    dotenvVars: ${file(configs.js)}

functions:
  catalogBatchProcess:
    handler: handler.catalogBatchProcess
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - CatalogItemsQueue
              - Arn
          batchSize: 5
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                productId: true
  getAllProducts:
    handler: handler.getAllProducts
    events:
      - http:
          path: products
          method: get
          cors: true
  createProduct:
    handler: handler.createProduct
    events:
      - http:
          path: products
          method: post
          cors: true
          request:
            schema:
              application/json: ${file(src/schemas/createProductSchema.json)}
resources:
  Resources:
    CatalogItemsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
    CreateProductTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic
    TopicEmailSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: aghasyaneliza@gmail.com
        Protocol: email
        TopicArn:
          Ref: CreateProductTopic
